name: HFGI
channels:
  - 3dhubs
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.4.13=h06a4308_1
  - certifi=2020.12.5=py36h06a4308_0
  - cloog=0.18.0=0
  - cmake=3.14.0=h52cb24c_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - expat=2.4.1=h2531618_2
  - freetype=2.10.4=h5ab3b9f_0
  - gcc-5=5.2.0=1
  - gmp=6.2.1=h2531618_2
  - intel-openmp=2021.2.0=h06a4308_610
  - isl=0.12.2=0
  - jpeg=9b=h024ee3a_2
  - krb5=1.17.1=h173b8e3_0
  - lcms2=2.12=h3be6417_0
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.2=he6710b0_1
  - olefile=0.46=py36_0
  - openssl=1.1.1k=h27cfd23_0
  - pip=20.0.2=py36_3
  - python=3.6.7=h0371630_0
  - python_abi=3.6=1_cp36m
  - readline=7.0=h7b6447c_5
  - rhash=1.4.1=h3c74f83_1
  - setuptools=46.4.0=py36_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.9.0
    - blurhash==1.1.4
    - boost==0.1
    - cachetools==4.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - dataclasses==0.8
    - decorator==4.4.2
    - dlib==19.22.0
    - future==0.18.2
    - google-auth==1.15.0
    - google-auth-oauthlib==0.4.1
    - greenlet==1.1.0
    - grpcio==1.29.0
    - idna==2.9
    - imageio==2.8.0
    - importlib-metadata==1.6.0
    - kiwisolver==1.2.0
    - markdown==3.2.2
    - mastodon-py==1.5.1
    - matplotlib==3.2.1
    - mxnet==1.6.0
    - networkx==2.4
    - ninja==1.10.0.post2
    - numpy==1.18.4
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - pillow==7.1.2
    - protobuf==3.12.1
    - pyaml==20.4.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-graphviz==0.8.4
    - python-magic==0.4.24
    - pytorch-lightning==0.7.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.17.2
    - scipy==1.4.1
    - sqlalchemy==1.4.15
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==1.9
    - tifffile==2020.5.25
    - torch==1.7.0
    - torchvision==0.8.0
    - tqdm==4.46.0
    - typing-extensions==3.10.0.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - zipp==3.1.0
